runtime: nodejs16
service: app

instance_class: F1

# automatic_scaling:
#   min_instances: 0
#   max_instances: 1
#   min_idle_instances: 0
#   max_idle_instances: 1

handlers:
  # Serve auth route with custom user name present
  - url: /auth/login/*.*
    static_files: dist/syfted/index.html
    upload: dist/syfted/index.html
    secure: always
    redirect_http_response_code: 301
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/syfted/\1
    upload: dist/syfted/(.*\..+)$
    secure: always
    redirect_http_response_code: 301
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/syfted/index.html
    upload: dist/syfted/index.html
    secure: always
    redirect_http_response_code: 301

  # - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  #   static_files: dist/syfted/\1
  #   upload: dist/syfted/(.*)(|\.map)

  # - url: /(.*)
  #   static_files: dist/syfted/index.html
  #   upload: dist/syfted/index.html
